const mensagens = [
    "☕ Segura aí, Maestro! Estou coando essa resposta com carinho...",
    "Já já fica pronto! Igual café passado na hora, só mais um gole de paciência!",
    "Espere só um pouquinho, estou colocando açúcar na resposta...",
    "☕ A cafeína tá subindo... Enviando sua resposta com energia!",
    "Calma, Maestro, tô só esquentando a água!",
    "⏳ Um instante... estou moendo os dados fresquinhos pra você!",
    "Esse comando tá no ponto... igual café preto sem açúcar!",
    "Aguenta firme, Maestro, já tô servindo sua dose de código quente!",
    "🍩 Enquanto espera, aceita uma rosquinha? A resposta tá quase pronta!",
    "Tô preparando essa com a força de um expresso duplo!",
    "☕ A inteligência aqui é artificial, mas o cafezinho é de verdade!",
    "Já ouvi seu pedido, tô passando... quer com leite ou sem?",
    "Comando recebido! Vou coar essa informação como se fosse café gourmet!",
    "Só mais um gole de paciência... Enviando já!",
    "Maestro, esse vai com aroma de café novo. Já vai chegar!",
    "Tô fervendo aqui... mais quente que bule de vó!",
    "Café pronto e resposta a caminho, Maestro!",
    "Tô embalando sua mensagem com cheiro de café fresco.",
    "É rapidinho, só tô limpando o pó... de café!",
    "Essa resposta vai com um toque de caramelo e bytes torrados.",
    "Tá sentindo o cheirinho? É sua resposta chegando!",
    "Tô quase lá... igual café coado no pano!",
    "☕ Esse comando me deu energia! Respondendo já!",
    "Maestro, se fosse café instantâneo já tava pronto... Mas eu sou raiz!",
    "Já já tá na xícara, quer uma resposta forte ou suave?",
    "Mais rápido que uma dose de café duplo no fim do expediente!",
    "Respondi antes da última gota cair do coador, olha só!",
    "Quase queimando os circuitos de tão quente essa resposta, Maestro!",
    "Maestro, comando aceito! Misturando bytes com café e... enviado!",
    "Essa resposta tá fresquinha, acabou de sair da cafeteira!"
];

module.exports = mensagens;
